/**
 * 2019/1/26 下午9:18
 */

const EVENT = {
    PING: 'PING',
    PONG: 'PONG',
    ENTER_ROOM: 'ENTER_ROOM',
    PUT_CARD: 'PUT_CARD_12',
    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
    RECEIVE_CHAT_MESSAGE: 'RECEIVE_CHAT_MESSAGE',
    NEXT_ROUND: 'NEXT_ROUND'
}

module.exports = {
    port: 8079,
    EVENT,
}
